name: qr_code_customizer
description: A Flutter application for customizing QR codes.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  provider: ^6.0.0
  image_picker: ^1.0.4
  http: ^1.3.0  # Updated to be compatible with google_fonts 6.1.0
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.1.0
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  image: ^4.0.15
  webview_flutter: ^4.4.2
  mobile_scanner: ^3.5.1
  vibration: ^3.1.3
  glassmorphism: ^2.0.0
  flutter_layout_grid: ^1.0.3
  flutter_animate: ^4.2.0
  responsive_framework: ^0.2.0
  table_calendar: ^3.0.8   # â† aggiunto

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/sfondo_bottone.png
    - assets/images/sfondo_bottone2.png
    - assets/backgrounds/  # include all background patterns

